# Generated by Django 5.0.4 on 2024-05-12 09:57

import autoslug.fields
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='neetug_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ')], default='MCQ', max_length=10)),
                ('subject', models.CharField(choices=[('BIOLOGY', 'BIOLOGY'), ('PHYSICS', 'PHYSICS'), ('CHEMISTRY', 'CHEMISTRY')], default='', max_length=10)),
                ('from_class', models.CharField(choices=[('Class 11', 'Class 11'), ('Class 12', 'Class 12')], default='', max_length=10)),
                ('chapter', models.CharField(default='', max_length=50)),
                ('topic', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('question_text', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, default='', max_length=5000, null=True)),
                ('diagram_or_illustration', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='neetug.models/')),
                ('pyq_Last_asked_in', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='neetug_testseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=5000)),
                ('instructions', models.CharField(max_length=5000)),
                ('fees', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('premium', models.BooleanField(default=True)),
                ('valid_till', models.DateTimeField()),
                ('remark', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='neetug_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neetug.neetug_question')),
            ],
        ),
        migrations.CreateModel(
            name='neetug_testseries_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('syllabus', tinymce.models.HTMLField(max_length=5000)),
                ('maximum_marks', models.CharField(max_length=5)),
                ('negative_marking', models.BooleanField(default=False)),
                ('marks_per_correct_answer', models.IntegerField()),
                ('marks_per_wrong_answer', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('remark', models.CharField(max_length=100)),
                ('exam_questions', models.CharField(default='', max_length=100000, null=True)),
                ('testseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neetug.neetug_testseries')),
            ],
        ),
    ]
