# Generated by Django 5.0.4 on 2024-05-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neetug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neetug_option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='neetug.neetug_question'),
        ),
    ]
