# Generated by Django 5.0.4 on 2024-06-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neetug', '0003_testquestion_userresponse_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='neetug_question',
            name='question_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
