# Generated by Django 5.0.4 on 2024-06-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neetug', '0004_neetug_question_question_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neetug_question',
            name='question_code',
            field=models.CharField(blank=True, default='192071', max_length=10, null=True),
        ),
    ]
