# Generated by Django 5.0.4 on 2024-06-10 16:59

import neetug.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neetug', '0005_alter_neetug_question_question_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neetug_question',
            name='question_code',
            field=models.CharField(blank=True, default=neetug.models.generate_random_code, max_length=10, null=True),
        ),
    ]
