# Generated by Django 5.0.4 on 2024-07-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='class',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_subject',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectiveQuestion',
        ),
        migrations.DeleteModel(
            name='UploadedPDF',
        ),
    ]
