# Generated by Django 5.0.4 on 2024-07-14 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_convert',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_account_type', models.CharField(default='', max_length=10)),
                ('requested_account_type', models.CharField(default='', max_length=10)),
                ('request_status', models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=10)),
                ('declined_reason', models.CharField(choices=[('Identity Proof Expired', 'Identity Proof Expired'), ('Invalid ID', 'Invalid ID'), ('Uploaded ID is not clear', 'Uploaded ID is not clear'), ('Full Identity was not uploaded', 'Full Identity was not uploaded'), ('Photo not clear in Identity', 'Photo not clear in Identity'), ('Mobile number not available in Identity', 'Mobile number not available in Identity'), ('Violation of Policy', 'Violation of Policy')], default='Pending', max_length=500)),
                ('id_proof', models.FileField(default=None, upload_to='accounts.models/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('temp_field', models.CharField(default='temp', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
