# Generated by Django 5.0.4 on 2024-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_email_verification_data',
            name='verification_code',
            field=models.CharField(default='612409', max_length=10),
        ),
    ]
