# Generated by Django 5.0.4 on 2024-04-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_verification_data_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_email_verification_data',
            name='verification_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
