# Generated by Django 5.0.4 on 2024-07-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_convert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_convert',
            name='id_proof',
            field=models.FileField(default=None, upload_to='id_proofs/'),
        ),
    ]
