# Generated by Django 5.0.4 on 2024-04-19 10:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('exam_code', models.CharField(max_length=10)),
                ('description', tinymce.models.HTMLField(max_length=5000)),
                ('latest_updates', models.CharField(max_length=5000)),
                ('exam_added_on', models.DateTimeField(auto_now_add=True)),
                ('exam_last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
