# Generated by Django 5.0.4 on 2024-06-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator2', '0002_test_alter_question_pyq_teacher_testquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='test_generator2.module'),
        ),
    ]
