# Generated by Django 5.0.4 on 2024-06-19 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator2', '0003_alter_question_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_generator2.module'),
        ),
    ]
