# Generated by Django 5.0.4 on 2024-06-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator2', '0008_textbook_class_associated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbook',
            old_name='class_associated',
            new_name='class_instance',
        ),
    ]
