# Generated by Django 5.0.4 on 2024-06-23 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator2', '0010_question_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='textbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_generator2.textbook'),
        ),
    ]
