# Generated by Django 5.0.4 on 2024-07-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator2', '0011_testquestion_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_diagram_or_illustration',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='test_generator2/'),
        ),
        migrations.AddField(
            model_name='question',
            name='solution_diagram_or_illustration',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='test_generator2/'),
        ),
    ]
