# Generated by Django 5.0.4 on 2024-07-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator2', '0012_question_question_diagram_or_illustration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_diagram_or_illustration',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='test_generator2/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution_diagram_or_illustration',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='test_generator2/'),
        ),
    ]
