# Generated by Django 5.0.4 on 2024-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator2', '0013_alter_question_question_diagram_or_illustration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_instructions',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_time_in_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='test',
            name='watermark_text',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
